version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-turismo
    restart: always
    ports:
      - 27017:27017
    command: "--replSet rs0"

  mongo-express:
    image: mongo-express
    container_name: mongo-express-turismo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root